# Generated by Django 6.0.1 on 2026-01-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docName', models.CharField(default='default', max_length=25)),
                ('docSpecialization', models.CharField(default='default', max_length=25)),
                ('docHospital', models.CharField(default='default', max_length=25)),
                ('docExperience', models.IntegerField(default=999)),
            ],
        ),
    ]
